<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА</u></b>

Роман, доброго дня! рад приветствовать тебя вновь) <br />
(А дальше - шаблонная часть, как ты заметил по другим спринтам)<br>
<br />
Меня зовут Николай Шавлюго. <br />И на этом этапе твоего движения к новой профессии от меня будут комментарии по написанному коду. <br />Чтобы меньше "мусорить эфир" и чтобы максимально наглядно отделяться от основного кода, есть предложение условиться в некоторых обозначениях:<br /> <br />
<u><b>ТАКОЙ ШРИФТ</b></u> - всегда начало комментария <br />
<font color='green'>такой шрифт</font> - комментарии о том, что всё ОК <br/>
<font color='orange'>такой шрифт</font> - комментарии о том, что всё ОК по результату,<br> однако есть на что обратить внимание в плане применения техник, или есть способы сделать более короткий или быстрый код <br/>
<font color='red'>такой шрифт</font> - комментарии о том, что есть критичный момент, влияющий на бизнес-результат проекта.<br/>
</font><br /><br />
<font color='green'>Моей целью является не "уличить" в не знании, а просто высказать сверху твоих знаний - свой опыт, что бы ты мог использовать его для своего дальнейшего успеха) И очень здорово будет, если тебе удастся задавать вопросы, да и вообще - всячески доставать меня, если я по каким-то причинам не приму проект:) При этом, из своего опыта скажу, хорошо и важно, когда переписка ревьюера и студента - сохраняется на следующие проекты и даже на будущую практическую деятельность.<br>
<BR> В ПУТЬ!<br>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.

In [34]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score
import random

## Загрузка данных

Загрузим данные:

In [35]:
df = pd.read_csv('https://code.s3.yandex.net/datasets/insurance.csv') 

In [36]:
df.head()

Пол  Возраст  Зарплата  Члены семьи  Страховые выплаты
0    1     41.0   49600.0            1                  0
1    0     46.0   38000.0            1                  1
2    0     29.0   21000.0            0                  0
3    0     21.0   41700.0            2                  0
4    1     28.0   26100.0            0                  0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
Пол                  5000 non-null int64
Возраст              5000 non-null float64
Зарплата             5000 non-null float64
Члены семьи          5000 non-null int64
Страховые выплаты    5000 non-null int64
dtypes: float64(2), int64(3)
memory usage: 195.4 KB


Переименуем столбцы

In [38]:
df.columns = ['sex', 'age', 'income', 'family', 'payout']

Изменим тип данных

In [39]:
df.age = df.age.astype(int)
df.income = df.income.astype(int)

Посмотрим основные статистические характеристики

In [40]:
df.describe().T

count        mean          std     min      25%      50%      75%  \
sex     5000.0      0.4990     0.500049     0.0      0.0      0.0      1.0   
age     5000.0     30.9528     8.440807    18.0     24.0     30.0     37.0   
income  5000.0  39916.3594  9900.082063  5300.0  33300.0  40200.0  46600.0   
family  5000.0      1.1942     1.091387     0.0      0.0      1.0      2.0   
payout  5000.0      0.1480     0.463183     0.0      0.0      0.0      0.0   

            max  
sex         1.0  
age        65.0  
income  79000.0  
family      6.0  
payout      5.0

<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА</u></b>
</font>
<font color='green'><br>
Данные на базе) ОК, хорошо, когда есть аналитическая культура - обязательно делать первичный анализ данных, не смотря на проект)

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

Создадим модель, сохраним её в переменной model и обучим. Найдем её предсказания на обучающей выборке и сохраним их в переменной predictions. Вычислим по MSE и напечатаем на экране значение метрики R2

<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА</u></b>
</font>
<font color='red'><br>
У матриц есть такие свойста<br>
- ($A(BC) = (AB)C$); это свойство ассоциативности (сочетательности) матриц<br>
- $(P^T)^{-1} = (P^{-1})^T$; то есть: транспортированная обратная матрица есть обратная матрица транспортированная <br>
- $(AB)^T = B^T A^T$; то есть: транспонированное произведение матриц равно произведению транспонированных матриц <br>
- $(AB)^{-1} = B^{-1} A^{-1}$,то есть: обратная матрица от произведения двух матриц равна обратной матрицы B(второй) к обратной матрице А(первой)<br>
- $P P^{-1} = E$ ; умножение матрицы на свою обратную - есть единичная матрица.<br>
    
И вот ожидается алгебраическое доказательсто на их основе.<br>
    
Через выражение (при подстановке $w' = ((XP)^T XP)^{-1} (XP)^T y$) надо дойти до $w' = P^{-1}w$ , где $w = (X^T X)^{-1} X^T y$ Это и будет доказательством. При этом $ (X^T X)^{-1}$ - не надо раскрывать, так как для неквадратных матриц ($X$ и $X^T$) обратных матриц не существует

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА</u></b>
</font>
<font color='red'><br>Не понял их просто перемножить необходимо? Неочевидность задания это так задумано? Или я где то проглядел этот момент<br>


<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА 2</u></b>
</font>
<font color='red'><br>Привет, Роман!<br>
И перемножить тоже) вот ниже приведу само алгебраическое доказательство без 2-х строк. Вот так оно и будет выглядеть)<br>
    
В общем-то вот это надо тебе наладить и вроде всё  порядке. 

$$
w' = ((XP)^T XP)^{-1} (XP)^T y
$$
$$
w' = (P^T (X^T X) P)^{-1} (XP)^T y
$$
$$
.......
$$
$$
.......
$$
$$
w' = P^{-1} (X^T X)^{-1} E X^T y
$$

In [41]:
features = df.drop('payout', axis=1)
target = df['payout']

In [42]:
class LinearRegression:
    def fit(self, train_features, train_target):
        X = np.concatenate((np.ones((train_features.shape[0], 1)), train_features), axis=1)
        y = train_target
        w =  np.linalg.inv(X.T @ X) @ X.T @ y
        
        self.w = w[1:]
        self.w0 = w[0]

    def predict(self, test_features):
        return test_features.dot(self.w) + self.w0
    
model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
print(r2_score(target, predictions))

0.42494550308169177


In [43]:
model.w

array([ 7.92580563e-03,  3.57083050e-02, -1.70081903e-07, -1.35676627e-02])

In [44]:
model.w0

-0.9382354469755936

Выполним умножение матриц для проверки их свойств:

$$
w' = ((XP)^T XP)^{-1} (XP)^T y
$$
$$
w' = (P^T (X^T X) P)^{-1} (XP)^T y
$$
$$
w' = (P^T P)^{-1} (X^T X)^{-1} (XP)^T y
$$
$$
w' = P^{-1} (X^T X)^{-1}(P^{-1}P)^{T} X^T y
$$
$$
w' = P^{-1} (X^T X)^{-1} E X^T y
$$

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА</u></b>
</font>
<font color='red'><br> 1,2,3 при проверке отличаются почему то, 4 и 5 равны. Посмотри пожалуйста что не так делаю <br>



<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА 3</u></b>
</font>
<font color='green'><br>Доброго вечера, Роман.<br>
Почти так. Вот ниже оставил окончательный вараинт.<br>
    
Т.е. всё в общем-то. пришли к концу с этим) Отсылаю на ознакомление.

$$
w' = ((XP)^T XP)^{-1} (XP)^T y
$$
$$
w' = (P^T (X^T X) P)^{-1} (XP)^T y
$$
$$
w' = (P^T (X^T X) P)^{-1} P^T X^T y
$$
$$
w' = P^{-1} (X^T X)^{-1} (P^T)^{-1} P^T X^T y
$$
$$
w' = P^{-1} (X^T X)^{-1} E X^T y
$$

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА 2</u></b>
</font>
<font color='red'><br>вот это я деградировал Николай, а ведь 10 лет назад у меня отлично автоматом было по вышке все 4 семестра<br>



<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА 4</u></b>
</font>
<font color='green'><br>
Абсолютно не согласен) Наш голова (или что там в ней...) устроена так, что мы хорошо помним только то, в чем часто пользуемся. Надо признать, что линейная матричная алгебра - это не "завсегдатый" нашего модельного застолья:)<br>
    
Поэтому, тут всё занономерно)<br>
Но теперь всё - ты справился со всем этим.<br>
Да и весь проект - на уровне, на самом деле.<br>
    
Если рассматривать передачу данных третьим лицам, то к преимуществам данного подхода можно отнести, в первую очередь, ощутимую экономию ресурсов по сравнению с некоторыми известными алгоритмами шифрования, в особенности это касается ассиметричных алгоритмов с достаточно длинными ключами (AES, RSA), которые требуют много процессорного времени.<br><br>
    
К главному недостатку подхода можно отнести увеличение сложности проверки на вырожденность преобразования с ростом количества признаков в выборке. В рассмотренном случае необходимо подобрать подходящую матрицу размера  4×4 . Однако, если признаки будут исчисляться тысячами, что в теории всегда надо положить, то расчет соответствующих определителей может быть крайне ресурсозатратным. Но и эту проблему можно будет решить)<br><br>
    
Если есть время и желание, то можно воту этот маткриал просмотреть:<br>
Обзоры по применению криптографии в машинном обучении: https://arxiv.org/pdf/1902.04109.pdf, https://www.researchgate.net/publication/342746786_Some_Applications_of_Machine_Learning_in_Cryptography
Подробнее про аналогичный алгоритм: https://www.cs.cmu.edu/~rjhall/JOS_revised_May_31a.pdf<br><br>
<font color='green'><font color='green'>
Спасибо) Успешного дальнейшего обучения

In [45]:
X = np.concatenate((np.ones((features.shape[0], 1)), features), axis=1)
y = target
P_sq = np.random.random((5, 5))
P_sq.shape

(5, 5)

In [46]:
w = np.linalg.inv(X.T @ X) @ X.T @ y
w

array([-9.38235447e-01,  7.92580563e-03,  3.57083050e-02, -1.70081903e-07,
       -1.35676627e-02])

In [47]:
#1
w1 = np.linalg.inv((X @ P_sq).T @ (X @ P_sq)) @ (X @ P_sq).T @ y 
w1

array([-1.38534319, -4.10963316,  1.15275009,  1.29317599,  1.5981363 ])

In [48]:
#2
w1 = np.linalg.inv(P_sq.T @ (X.T @ X) @ P_sq) @ (X @ P_sq).T @ y 
w1

array([-1.38551314, -4.11013348,  1.15289633,  1.29332878,  1.59833606])

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА 2</u></b>
</font>
<font color='red'><br> А почему веса немного отличаются? <br>



In [52]:
#3
w1 = np.linalg.inv(P_sq.T @ (X.T @ X) @ P_sq) @ (P_sq.T @ X.T) @ y 
w1

array([-1.38551314, -4.11013348,  1.15289633,  1.29332878,  1.59833606])

In [55]:
#4
w1 = np.linalg.inv(P_sq) @ np.linalg.inv(X.T @ X) @ np.linalg.inv(P_sq.T) @ P_sq.T @ X.T @ y 
w1

array([-1.38549627, -4.11008305,  1.15288143,  1.29331363,  1.59831605])

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА 2</u></b>
</font>
<font color='red'><br> и тут отличаются <br>



In [56]:
#5
w1 = np.linalg.inv(P_sq) @ np.linalg.inv(X.T @ X) @ X.T @ y
w1

array([-1.38549627, -4.11008305,  1.15288143,  1.29331363,  1.59831605])

In [ ]:
w1 = np.linalg.inv(P_sq) @ w
w1

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА</u></b>
</font>
<font color='red'><br> перемножил, сравнил, или эти веса надо далее использовать? <br>



При подстановке $w' = ((XP)^T XP)^{-1} (XP)^T y$) получим $w' = P^{-1}w$ , где $w = (X^T X)^{-1} X^T y$ 

$w' = $w

**Ответ:** r2 = 0.424

**Обоснование:** Значение R2 неотрицательное, не равно нулю и не больше единицы. Значит, линейная регрессия работает.

<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА</u></b>
</font>
<font color='green'><br>ОК)

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА</u></b>
</font>
<font color='red'><br>))) из тренажера вывод слово в слово, решил что сгодится<br>



<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА 2</u></b>
</font>
<font color='green'><br>:)

## Алгоритм преобразования

**Алгоритм**
Умножим матрицу признаков на рандомную матрицу

In [ ]:
A = df.values

In [ ]:
A.shape

In [ ]:
P = np.random.random((4, 4))
P

<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА</u></b>
</font>
<font color='red'><br>ВОт тут, обычно, создают матрицу 4х4. А потом проверяют на обратимость)

Квадратная матрица обратима:

In [ ]:
np.linalg.inv(P)

In [ ]:
E = P * np.linalg.inv(P)
E / np.linalg.inv(P)

Нашли единичную матрицу и доказали алгебраически свойство обратимости

In [ ]:
A[:,:4].shape

In [ ]:
P.shape

In [ ]:
A_coded = A[:,:4] * P[3:,:]
A_coded.shape

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА</u></b>
</font>
<font color='red'><br> ок, 4х4 матрица есть для проверки обратимости, а чтобы зашифровать надо подрезать ее на 1х4 все таки? <br>


<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА 2</u></b>
</font>
<font color='green'><br>Нет, не надо)

In [ ]:
A_coded

In [ ]:
df_coded = pd.DataFrame(A_coded)
df_coded.shape

**Обоснование**

Данные зашифрованы с помощью рандомной матрицы 1 на 4

## Проверка алгоритма

Обучим модель на преобразованных признаках:

In [ ]:
features = df_coded.copy()

model = LinearRegression()
model.fit(features, target)
predictions = model.predict(features)
print(r2_score(target, predictions))

<div style="background: #ffeeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА</u></b>
</font>
<font color='green'><br>Вот так рекомендуют, через копирование создавать:<br>
features = df_coded.copy()

<div style="background: #fffff; padding: 5px; border: 10px solid red; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ СТУДЕНТА</u></b>
</font>
<font color='red'><br>Добавил<br>
features = df_coded.copy()

**Вывод** алгоритм реализован и проверен, проведено сравнение моделей до и после преобразования: качество не изменилось.

<div style="background: #cceeaa; padding: 5px; border: 1px solid green; border-radius: 5px;">
    <font color='green'> <b><u>КОММЕНТАРИЙ РЕВЬЮЕРА</u></b>
</font>
<font color='green'><br>
Роман, идейно - именно такой движение по всем шагам. Да и сама практическая цель достигнута, можно сказать.<br>
Тут всё верно. Есть несколько моментов для дополнений:<br>
    
1) В разделе "Умножение матриц" ожидается алгебраическое доказательство. В тексте постарался описать проблематику.<br>
2) Создание матрицы 4х4 и проверка на обратимость<br>
<font color='red'><br>
Посмотри, пожалуйста)<br><font color='green'><font color='green'>
Спасибо) Буду ждать.

## Чек-лист проверки

Поставьте 'x' в выполненных пунктах. Далее нажмите Shift+Enter.

- [x]  Jupyter Notebook открыт
- [x]  Весь код выполняется без ошибок
- [x]  Ячейки с кодом расположены в порядке исполнения
- [x]  Выполнен шаг 1: данные загружены
- [x]  Выполнен шаг 2: получен ответ на вопрос об умножении матриц
    - [ ]  Указан правильный вариант ответа
    - [ ]  Вариант обоснован
- [x]  Выполнен шаг 3: предложен алгоритм преобразования
    - [x]  Алгоритм описан
    - [x]  Алгоритм обоснован
- [x]  Выполнен шаг 4: алгоритм проверен
    - [x]  Алгоритм реализован
    - [x]  Проведено сравнение качества моделей до и после преобразования